apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: server
          image: olegmukhin/identity-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081

---